- name: create resource group
  azure_rm_resourcegroup:
    name: "{{ ResourceName }}"
    location: SoutheastAsia
  ignore_errors: True

- name: Create storage account
  azure_rm_storageaccount:
    resource_group: "{{ ResourceName }}"
    name: "{{ AccountName }}"
    account_type: "{{ AccountType }}"
  ignore_errors: True

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ ResourceName }}"
    name: "{{ VnetName }}"
    address_prefixes: "{{ VnetSpace }}"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ ResourceName }}"
    name: "{{ SubnetName }}"
    address_prefix: "{{ SubnetSpace }}"
    virtual_network: "{{ VnetName }}"

- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: "{{ ResourceName }}"
    allocation_method: "{{ PublicIPMethod }}"
    name: "{{ PIPName }}"

- name: Create security group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ ResourceName }}"
    name: "{{ SGName }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      - name: RDP
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 102
        direction: Inbound

- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "{{ ResourceName }}"
    name: "{{ NICName }}"
    virtual_network: "{{ VnetName }}"
    subnet: "{{ SubnetName }}"
    public_ip_name: "{{ PIPName }}"
    security_group: "{{ SGName }}"

- name: Create a VM with OS and multiple data managed disks
  azure_rm_virtualmachine:
    resource_group: "{{ ResourceName }}"
    name: "{{ VMName }}"
    vm_size: "{{ VMSize }}"
    admin_username: "{{ AdminUser }}"
    admin_password: "{{ AdminPassword }}"
    image:
      name: "{{ ImageName }}"
      resource_group: "{{ ImageResourceName }}"
